
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('quotes').del(),

    // Inserts seed entries
    knex('quotes').insert({id: 1, quote: 'It is our choices, Harry, that show what we truly are, far more than our abilities.', author: 'Dumbledore' }),
    knex('quotes').insert({id: 2, quote: 'It matters not what someone is born, but what they grow to be.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 3, quote: 'It does not do to dwell on dreams and forget to live.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 4, quote: 'There are all kinds of courage,” said Dumbledore smiling. “It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 5, quote: 'People find it far easier to forgive others for being wrong than being right.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 6, quote: 'We are only as strong as we are united, as weak as we are divided.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 7, quote: 'Differences of habit and language are nothing at all if our aims are identical and our hearts are open.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 8, quote: 'We cannot choose our fate, but we can choose others. Be careful in knowing that.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 9, quote: 'The world isn’t split into good people and Death Eaters. We’ve all got both light and dark inside us. What matters is the part we choose to act on. That’s who we really are.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 10, quote: 'It is important,” Dumbledore said, “to fight, and fight again, and keep fighting, for only then could evil be kept at bay, though never quite eradicated.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 11, quote: '“The truth.” Dumbledore sighed. “It is a beautiful and terrible thing, and should therefore be treated with great caution.”', author: 'Dumbledore'}),
    knex('quotes').insert({id: 12, quote: 'Curiosity is not a sin…but we should exercise caution with our curiosity.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 13, quote: 'Understanding is the first step to acceptance, and only with acceptance can there be recovery.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 14, quote: 'Youth cannot know how age thinks and feels, but old men are guilty if they forget what it was to be young.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 15, quote: 'Do not pity the dead, Harry, pity the living, and above all those who live without love.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 16, quote: 'It is the unknown we fear when we look upon death and darkness, nothing more.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 17, quote: '“Ah, music,” he said wiping his eyes. “A magic beyond all we do here.”', author: 'Dumbledore'}),
    knex('quotes').insert({id: 18, quote: 'Words are, in my not so humble opinion, our most inexhaustible source of magic, capable of both influencing injury, and remedying it.', author: 'Dumbledore'}),
    knex('quotes').insert({id: 19, quote: 'I don’t go looking for trouble, trouble usually finds me.', author: 'Harry'}),
    knex('quotes').insert({id: 20, quote: 'If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.', author: 'Sirius Black'}),
    knex('quotes').insert({id: 21, quote: 'Things we lose have a way of coming back to us in the end, if not always in the way we expect.', author: 'Luna Lovegood'}),
    knex('quotes').insert({id: 22, quote: 'Thoughts could leave deeper scars than almost anything else.', author: ''}),
    knex('quotes').insert({id: 23, quote: 'We are all human, aren’t we? Every human life is worth the same, and worth saving.', author: 'Kingsley Shacklebolt'}),
    knex('quotes').insert({id: 24, quote: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt'}),
    knex('quotes').insert({id: 25, quote: 'The most effective way to do it, is to do it.', author: 'Amelia Earhart'}),
    knex('quotes').insert({id: 26, quote: 'The power you have is to be the best version of yourself you can be, so you can create a better world.', author: 'Ashley Rickards'}),
    knex('quotes').insert({id: 27, quote: 'If you obey all the rules, you miss all the fun.', author: 'Katharine Hepburn'}),
    knex('quotes').insert({id: 28, quote: 'We can do no great things, only small things with great love.', author: 'Mother Teresa'}),
    knex('quotes').insert({id: 29, quote: 'The most common way people give up their power is by thinking they don’t have any.', author: 'Alice Walker'}),
    knex('quotes').insert({id: 30, quote: 'Life shrinks or expands in proportion to one’s courage.', author: 'Anais Nin'}),
    knex('quotes').insert({id: 31, quote: 'I’m not afraid of storms, for I’m learning to sail my ship.', author: 'Louisa May Alcott'}),
    knex('quotes').insert({id: 32, quote: 'Angry people are not always wise.', author: 'Jane Austen'}),
    knex('quotes').insert({id: 33, quote: 'There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises at every attempt to intimidate me.', author: 'Elizabeth Bennet'}),
    knex('quotes').insert({id: 34, quote: 'For what do we live, but to make sport for our neighbours, and laugh at them in our turn?', author: 'Mr Bennet'}),
    knex('quotes').insert({id: 35, quote: 'OH MR BENNET!!', author: 'Mrs Bennet / Hilary Roots'}),
    knex('quotes').insert({id: 36, quote: 'Many were increasingly of the opinion that they’d all made a big mistake in coming down from the trees in the first place. And some said that even the trees had been a bad move, and that no one should ever have left the oceans.', author: 'Douglas Adams'}),
    knex('quotes').insert({id: 37, quote: 'The ships hung in the sky in much the same way that bricks don’t', author: 'Douglas Adams'}),
    knex('quotes').insert({id: 38, quote: 'You know,” said Arthur, “it’s at times like this, when I’m trapped in a Vogon airlock with a man from Betelgeuse, and about to die of asphyxiation in deep space that I really wish I’d listened to what my mother told me when I was young.” “Why, what did she tell you?” “I don’t know, I didn’t listen.”', author: 'Douglas Adams'}),
    knex('quotes').insert({id: 39, quote: 'So long and thanks for all the fish.', author: 'Dolphins'}),
    knex('quotes').insert({id: 40, quote: 'Forty-two', author: 'Deep Thought'}),
    knex('quotes').insert({id: 41, quote: 'It is known that there are an infinite number of worlds, simply because there is an infinite amount of space for them to be in. However, not every one of them is inhabited. Therefore, there must be a finite number of inhabited worlds. Any finite number divided by infinity is as near to nothing as makes no odds, so the average population of all the planets in the Universe can be said to be zero. From this it follows that the population of the whole Universe is also zero, and that any people you may meet from time to time are merely the products of a deranged imagination.', author: 'Douglas Adams'}),
    knex('quotes').insert({id: 42, quote: 'In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.', author: 'Douglas Adams'}),
    knex('quotes').insert({id: 43, quote: 'Don’t Panic.', author: ''}),
    knex('quotes').insert({id: 44, quote: '“Cake or death?”', author: 'Church of England'}),
    knex('quotes').insert({id: 45, quote: 'Father, bless me for I have sinned, I did an original sin… I poked a badger with a spoon.', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 46, quote: 'I am an evil Giraffe.', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 47, quote: 'We will now sing forth, hymn 405, \'Oh God, what on earth is my hairdo all about?', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 48, quote: 'Never put a sock in a toaster.', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 49, quote: 'I\'m covered in bees!', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 50, quote: 'This is your captain speaking. Welcome aboard flight...one, from...here to there. We\'ll be cruising at a height of ten feet, going up to twelve and a half feet if we see anything big. And our copilot today is a flask of coffee.', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 51, quote: 'Tea and cake or death?', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 52, quote: 'Do you have a flag?', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 53, quote: 'No flag no country, you can\'t have one. That\'s the rule... that I just made up...', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 54, quote: 'If you\ve never seen an elephant ski then you\ve never been on acid...', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 55, quote: 'I like my women like I like my coffee. In a plastic cup...', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 56, quote: 'I\M COVERED IN BEES!', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 57, quote: 'Is this a sexy tune Mrs Badcrumble?', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 58, quote: 'Cannot access printer...', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 59, quote: 'I CAN ACCESS THE PRINTER! SEEE HOW MY HANDS TOUCH IT...', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 60, quote: 'Jeff, born on the first of Jeff, 19-Jefty jeff', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 71, quote: 'You made Baldrick a lord...', author: 'Blackadder'}),
    knex('quotes').insert({id: 72, quote: 'Baaalldrick... that\'s a pretty name...', author: 'Lord Percy'}),
    knex('quotes').insert({id: 73, quote: 'Give the likes of Baldrick the vote and we\'ll be back to cavorting druids, death by stoning and dung for dinner...', author: 'Blackadder'}),
    knex('quotes').insert({id: 74, quote: 'Oh, God. Fortune vomits on my eiderdown once more.', author: 'Blackadder'}),
    knex('quotes').insert({id: 75, quote: 'My life is strewn with cowpats from the devils own SATANIC HERD!', author: 'Blackadder'}),
    knex('quotes').insert({id: 76, quote: '"Am I jumping the gun, Baldrick, or are the words \'I have a cunning plan\' marching with ill-deserved confidence in the direction of this conversation?', author: 'Blackadder'}),
    knex('quotes').insert({id: 77, quote: 'To you, Baldrick, the Renaissance was something that just happened to other people, wasn\'t it?', author: 'Blackadder'}),
    knex('quotes').insert({id: 78, quote: 'I will return before you can say \'antidisestablishmentarianism\'.', author: 'Blackadder'}),
    knex('quotes').insert({id: 79, quote: 'This is not a game of who the fuck are you', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 80, quote: 'You\'ll need a tray...', author: 'Eddie Izzard'}),
    knex('quotes').insert({id: 81, quote: 'I have a cunning plan', author: 'Baldrick'}),
    knex('quotes').insert({id: 82, quote: 'Three things my lord my ye know of the wise woman! First, she is...  A WOMAN!', author: 'Mad old crone'}),
    knex('quotes').insert({id: 83, quote: 'Uh, guys? Olympus would be that way.', author: 'Hades'}),
    knex('quotes').insert({id: 84, quote: 'Somebody call IX-I-I!', author: 'Pain/panic'}),
    knex('quotes').insert({id: 85, quote: 'The string wont cut!!', author: 'The fates'}),
    knex('quotes').insert({id: 86, quote: 'Indoor plumbing. It\'s gonna be big...', author: 'The Fates'}),
    knex('quotes').insert({id: 87, quote: 'woah, is my hair out?', author: 'Hades'}),
    knex('quotes').insert({id: 88, quote: 'Honey, you mean "Hunk-ules!" Ooh, I\'d like to make some sweet music with him.', author: 'Muse'}),
    knex('quotes').insert({id: 89, quote: 'Ha-WA-ee', author: 'I can\'t even remember...'}),
    knex('quotes').insert({id: 90, quote: '"You can\'t, their immortal!" "Bingo! their immortal. so, first you gotta turn the little sunspot... mortal.', author: ''}),
    knex('quotes').insert({id: 91, quote: 'NOT MY DAUGHTER YOU BITCH', author: 'Molly Weasly'}),
    knex('quotes').insert({id: 92, quote: 'What a jolly good idea, I\'ll get right onto it!', author: 'Deskbot'}),
    knex('quotes').insert({id: 93, quote: 'Why are their no phones in China?...', author: 'Phil Brigham'}),
    knex('quotes').insert({id: 94, quote: 'You need your Inner Eye tested, if you ask me…', author: 'Harry'}),
    knex('quotes').insert({id: 95, quote: 'Draco Malfoy, the amazing bouncing ferret...', author: 'Ron Weasly'}),
    knex('quotes').insert({id: 96, quote: 'He can run faster than Severus Snape confronted with shampoo.', author: 'Fred Weasley'}),
    knex('quotes').insert({id: 97, quote: 'Everybody finished the song at different times. At last, only the Weasley twins were left singing along to a very slow funeral march', author: ''}),
    knex('quotes').insert({id: 98, quote: 'Hogwarts Hogwarts hoggy warty hogwarts teach us something please! Whether we be old or bald or young with saggy knees! Our heads could do with filling with some interesting stuff. For now their bare and full or air, dead flies and bits of fluff. So teach us things worth knowing! Bring back what we\'ve forgot. Just do you\'re best we\'ll do the rest and learn until our brains all rot', author: ''}),
    knex('quotes').insert({id: 99, quote: '“You haven’t got a letter on yours,” George observed. “I suppose she thinks you don’t forget your name. But we’re not stupid – we know we’re called Gred and Forge.”', author: 'Fred Weasley'}),
    knex('quotes').insert({id: 100, quote: 'Mr. Moony presents his compliments to Professor Snape, and begs him to keep his abnormally large nose out of other people\'s business.', author: 'Moony'}),
    knex('quotes').insert({id: 101, quote: 'Mr. Prongs agrees with Mr. Moony, and would like to add that Professor Snape is an ugly git.', author: 'Prongs'}),
    knex('quotes').insert({id: 102, quote: 'Mr. Padfoot would like to register his astonishment that an idiot like that ever became a professor.', author: 'Padfoot'}),
    knex('quotes').insert({id: 103, quote: 'Mr. Wormtail bids Professor Snape good day, and advises him to wash his hair, the slimeball.', author: 'Wormtail'}),
    knex('quotes').insert({id: 104, quote: '"I\'m not putting them on," said old Archie in indignation. "I like a healthy breeze \'round my privates, thanks."', author: 'Archie'}),
    knex('quotes').insert({id: 105, quote: '"I don\'t believe it! Oh, Ron, how wonderful! A prefect! That\'s everyone in the family!" "What are Fred and I, next-door neighbours?" said George indignantly, as his mother pushed him aside and flung her arms around her youngest son.', author: ''}),
    knex('quotes').insert({id: 106, quote: 'Dark cloud?!? is that what I\'m calling my plan? Dark Cloud?!', author: ''}),
    knex('quotes').insert({id: 107, quote: 'Wuld anyone like some... ham?', author: 'Sue'}),
    knex('quotes').insert({id: 108, quote: 'Hey, I\'ve been turned into a cow. Can I go home?', author: 'Palace Guard'}),
    knex('quotes').insert({id: 109, quote: 'Is that *my* voice? Oh, well', author: 'Yzma'}),
    knex('quotes').insert({id: 110, quote: 'Why do we even *have* that lever?', author: 'Yzma'}),
    knex('quotes').insert({id: 111, quote: 'OK, why does she even have that leve?', author: 'Kuzco'}),
    knex('quotes').insert({id: 112, quote: 'Pull the lever Kronk.         WRONG LEVERRRRR...', author: 'Yzma'}),
    knex('quotes').insert({id: 113, quote: 'My spinach puffs!!', author: 'Kronk'}),
    knex('quotes').insert({id: 114, quote: 'I\'m sorry, but you\'ve thrown off the Emperor\'s groove.', author: 'Palace Guard'}),
    knex('quotes').insert({id: 115, quote: 'We realize the importance of our voices only when we are silenced.', author: 'Malala Yousafzai'}),
    knex('quotes').insert({id: 116, quote: 'You take your life in your own hands, and what happens? A terrible thing: no one to blame.', author: 'Erica Jong'}),
    knex('quotes').insert({id: 117, quote: 'Imagine the terrifying sight of a hundred thousand hedgehogs staring at you in silence.', author: 'Marcus Bridgestock'}),
    knex('quotes').insert({id: 118, quote: 'I was expecting some more willies', author: 'Nell Brigham'}),
    knex('quotes').insert({id: 119, quote: 'Dreckly is not a word but a way of life', author: 'Anna Brigham'})


  );
};
